export type NatureWorld1000Collection = 'living-sanctuaries' | 'geological-wonders';

export type NatureWorld1000Row = readonly [
  index: number,
  icon: string,
  name: string,
  collection: NatureWorld1000Collection,
];

/**
 * Worlds 901-1000 deliberately add two scene grammars that were underrepresented
 * in the original 900-world Atlas: ecological relationships at habitat scale and
 * geological structures at landscape/cave scale. These are authored names, not
 * palette permutations, so each world still compiles to a deterministic scene,
 * seed, interaction plan, and World Loom runtime.
 */
export const NATURE_WORLDS_901_1000: NatureWorld1000Row[] = [
  [901, '🌫️', 'mist-fed cloud forest bromeliad basin', 'living-sanctuaries'],
  [902, '🌿', 'mangrove nursery at spring tide', 'living-sanctuaries'],
  [903, '🦦', 'kelp canopy otter refuge', 'living-sanctuaries'],
  [904, '🐢', 'seagrass turtle nursery', 'living-sanctuaries'],
  [905, '💧', 'vernal pool salamander meadow', 'living-sanctuaries'],
  [906, '🌾', 'prairie bison wallow after rain', 'living-sanctuaries'],
  [907, '🐝', 'alpine pollinator meadow in bloom', 'living-sanctuaries'],
  [908, '🌴', 'desert oasis date palm refuge', 'living-sanctuaries'],
  [909, '🦫', 'beaver wetland willow mosaic', 'living-sanctuaries'],
  [910, '🦀', 'saltmarsh fiddler crab channels', 'living-sanctuaries'],
  [911, '🪸', 'coral nursery on a shallow reef', 'living-sanctuaries'],
  [912, '🦋', 'monarch butterfly milkweed corridor', 'living-sanctuaries'],
  [913, '🐟', 'salmon spawning gravel riffle', 'living-sanctuaries'],
  [914, '🪶', 'heron rookery in flooded cypress', 'living-sanctuaries'],
  [915, '🌲', 'old-growth snag woodpecker habitat', 'living-sanctuaries'],
  [916, '🏖️', 'dune grass shorebird nesting hollow', 'living-sanctuaries'],
  [917, '🪷', 'lotus pond dragonfly nursery', 'living-sanctuaries'],
  [918, '🌱', 'peat bog sundew microhabitat', 'living-sanctuaries'],
  [919, '🌺', 'rainforest epiphyte orchid canopy', 'living-sanctuaries'],
  [920, '🪵', 'mossy nurse log seedling cradle', 'living-sanctuaries'],
  [921, '🦇', 'bat-pollinated cactus night garden', 'living-sanctuaries'],
  [922, '🐘', 'elephant watering hole mud basin', 'living-sanctuaries'],
  [923, '🦒', 'giraffe acacia browsing grove', 'living-sanctuaries'],
  [924, '🦭', 'sea lion kelp rock refuge', 'living-sanctuaries'],
  [925, '🦪', 'oyster reef tidal filtration bed', 'living-sanctuaries'],
  [926, '🐚', 'mussel bed clear-water shallows', 'living-sanctuaries'],
  [927, '🌼', 'prairie dog wildflower colony', 'living-sanctuaries'],
  [928, '🐼', 'red panda bamboo hillside refuge', 'living-sanctuaries'],
  [929, '🦧', 'orangutan fig-tree feeding canopy', 'living-sanctuaries'],
  [930, '🐸', 'frog chorus reed wetland', 'living-sanctuaries'],
  [931, '✨', 'firefly floodplain summer meadow', 'living-sanctuaries'],
  [932, '🐝', 'bee hotel lavender garden', 'living-sanctuaries'],
  [933, '🌺', 'hummingbird trumpet flower terrace', 'living-sanctuaries'],
  [934, '🐢', 'tortoise desert scrub shelter', 'living-sanctuaries'],
  [935, '❄️', 'lynx snowshoe hare boreal edge', 'living-sanctuaries'],
  [936, '🪶', 'crane migration rice wetland', 'living-sanctuaries'],
  [937, '🐟', 'eelgrass bay juvenile fish meadow', 'living-sanctuaries'],
  [938, '🐦', 'estuary mudflat shorebird feeding grounds', 'living-sanctuaries'],
  [939, '💧', 'forest spring amphibian seep', 'living-sanctuaries'],
  [940, '🦦', 'river otter logjam pool', 'living-sanctuaries'],
  [941, '🌳', 'cocoa shade forest biodiversity grove', 'living-sanctuaries'],
  [942, '☁️', 'coffee cloud forest bird corridor', 'living-sanctuaries'],
  [943, '🌰', 'oak savanna acorn deer clearing', 'living-sanctuaries'],
  [944, '🍄', 'woodland mushroom mycelium network', 'living-sanctuaries'],
  [945, '🏔️', 'alpine pika talus garden', 'living-sanctuaries'],
  [946, '🐧', 'penguin cliff moss colony', 'living-sanctuaries'],
  [947, '🐦', 'puffin cliff nesting meadow', 'living-sanctuaries'],
  [948, '🦀', 'tidal mangrove crab labyrinth', 'living-sanctuaries'],
  [949, '🐚', 'freshwater mussel river bend', 'living-sanctuaries'],
  [950, '✨', 'moonlit bioluminescent mangrove lagoon', 'living-sanctuaries'],

  [951, '♨️', 'travertine terrace hot spring', 'geological-wonders'],
  [952, '🪨', 'hexagonal basalt column coast', 'geological-wonders'],
  [953, '🏜️', 'gypsum crystal dune field', 'geological-wonders'],
  [954, '⛰️', 'limestone karst tower valley', 'geological-wonders'],
  [955, '💧', 'turquoise cenote sinkhole', 'geological-wonders'],
  [956, '🌿', 'lava tube skylight fern cave', 'geological-wonders'],
  [957, '🌋', 'volcanic fumarole sulfur field', 'geological-wonders'],
  [958, '🖤', 'obsidian glass lava flow', 'geological-wonders'],
  [959, '🪨', 'tufa tower alkaline lake', 'geological-wonders'],
  [960, '🏜️', 'hoodoo amphitheater at dawn', 'geological-wonders'],
  [961, '☀️', 'slot canyon light beam', 'geological-wonders'],
  [962, '🌊', 'wave-cut sea arch grotto', 'geological-wonders'],
  [963, '🪵', 'petrified wood badlands', 'geological-wonders'],
  [964, '🌈', 'rainbow mineral hot spring', 'geological-wonders'],
  [965, '🧊', 'glacial moulin blue shaft', 'geological-wonders'],
  [966, '❄️', 'ice cave crystal ceiling', 'geological-wonders'],
  [967, '🧊', 'hanging glacier serac maze', 'geological-wonders'],
  [968, '💦', 'braided meltwater outwash plain', 'geological-wonders'],
  [969, '🪨', 'granite exfoliation dome', 'geological-wonders'],
  [970, '🪨', 'balancing boulder desert pedestal', 'geological-wonders'],
  [971, '🪨', 'sandstone honeycomb tafoni wall', 'geological-wonders'],
  [972, '🪨', 'limestone pavement clint and grike', 'geological-wonders'],
  [973, '🌉', 'red rock natural bridge', 'geological-wonders'],
  [974, '🌿', 'giant sinkhole rainforest abyss', 'geological-wonders'],
  [975, '🌊', 'underground river marble cave', 'geological-wonders'],
  [976, '💎', 'quartz crystal cave chamber', 'geological-wonders'],
  [977, '💚', 'emerald malachite cavern wall', 'geological-wonders'],
  [978, '💜', 'amethyst cathedral geode', 'geological-wonders'],
  [979, '🧂', 'salt crystal cave passage', 'geological-wonders'],
  [980, '🌋', 'volcanic crater lake rim', 'geological-wonders'],
  [981, '⚫', 'black sand lava delta', 'geological-wonders'],
  [982, '♨️', 'geothermal geyser basin', 'geological-wonders'],
  [983, '🫧', 'mud volcano bubbling field', 'geological-wonders'],
  [984, '💧', 'travertine cave rimstone pools', 'geological-wonders'],
  [985, '💨', 'desert yardang wind-carved corridor', 'geological-wonders'],
  [986, '🏜️', 'singing sand dune crest', 'geological-wonders'],
  [987, '❄️', 'patterned permafrost polygon field', 'geological-wonders'],
  [988, '🧊', 'frozen methane bubble lake', 'geological-wonders'],
  [989, '🌊', 'wave-cut basalt blowhole', 'geological-wonders'],
  [990, '🐚', 'coral limestone sea cave', 'geological-wonders'],
  [991, '🌊', 'uplifted marine terrace', 'geological-wonders'],
  [992, '⛰️', 'folded rock anticline canyon', 'geological-wonders'],
  [993, '🪨', 'columnar rhyolite cliff', 'geological-wonders'],
  [994, '🎨', 'iron oxide painted hills', 'geological-wonders'],
  [995, '🔵', 'blue clay glacial badlands', 'geological-wonders'],
  [996, '🌊', 'marble karst river gorge', 'geological-wonders'],
  [997, '🏔️', 'dolomite alpine spire field', 'geological-wonders'],
  [998, '☄️', 'meteor impact crater salt pan', 'geological-wonders'],
  [999, '♨️', 'geothermal steam cave', 'geological-wonders'],
  [1000, '💎', 'crystal-clear subterranean lake', 'geological-wonders'],
];
